# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8637f5b641f942b902c6ff40e7086b3046d0a8939d062473e4956bc729babc3f6dc098364af25720d116d3508e7dce79561a06188f5a437d87daf20d636949b

test:
  secret_key_base: 5b42325e3fd0b96d4636e312465875b26bbed2b71be5773825d9be936067ab53967323639a63ea49bfcc5cf73c568c2d0d7d4a7175a45a7951245030af56cc97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
